vich_uploader:
    db_driver: orm
    mappings:
        property_photos:
            uri_prefix: /uploads/properties
            upload_destination: '%kernel.project_dir%/public/uploads/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer